### ISSUE TITLE
BUG: setting IdentificationMethod filter results in exception.

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#308]
If you set an Identification Method filter, you get the following exceptions:

> 11:17:31,228 ERROR [AWT-EventQueue-0] JDBCProfileDao:334 - A database exception occurred finding filtered nodes with parent id NULL
> org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [select profile.*, case when (profile.identification_method IN (?)) then 1 else case when profile.resource_type <> 2 and exists ( select children.node_id from profile_resource_node as children where children.prefix > profile.prefix and children.prefix < profile.prefix_plus_one and (children.identification_method IN (?))) then 2 else 0 end end as FilterStatus from profile_resource_node as profile where profile.parent_id is null]; An attempt was made to get a data value of type 'INTEGER' from a data value of type 'uk.gov.nationalarchives.droid.core.interfaces.IdentificationMethod'.; nested exception is java.sql.SQLDataException: An attempt was made to get a data value of type 'INTEGER' from a data value of type 'uk.gov.nationalarchives.droid.core.interfaces.IdentificationMethod'.
> 	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)
> 	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
> 	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
> 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712)
> 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:768)
> 	at uk.gov.nationalarchives.droid.profile.JDBCProfileDao.findProfileResourceNodes(JDBCProfileDao.java:319)
> 	at uk.gov.nationalarchives.droid.profile.ProfileInstanceManagerImpl.findRootProfileResourceNodes(ProfileInstanceManagerImpl.java:381)
> 	at uk.gov.nationalarchives.droid.profile.ProfileInstanceManagerImpl.findRootProfileResourceNodes(ProfileInstanceManagerImpl.java:325)
> 	at uk.gov.nationalarchives.droid.profile.ProfileManagerImpl.findRootNodes(ProfileManagerImpl.java:250)
> 	at uk.gov.nationalarchives.droid.gui.action.ApplyFilterToTreeTableAction.applyFilter(ApplyFilterToTreeTableAction.java:93)

**Comment by nishihatapalmer** [comment]
This affects any filter type which is an enum.

**Comment by nishihatapalmer** [comment]
PR with a fix has been created.

**Comment by nishihatapalmer** [comment]
Note:  I'm a bit suspicious of this fix.

Although it works, the way enums have been returned for filters is essentially unchanged since this was first written.

It looks like something else has changed in how enum values are mapped back to database integers somewhere else in the code.

So - while this seems to fix the issue, the fix may be in the wrong place.

**Comment by nishihatapalmer** [comment]
Although... it still may be the right fix.  I think this may be something which happened during the change over from hibernate (which mapped the objects itself) to JDBC directly - which was then replaced by JDBCTemplate.

Derby itself doesn't support enum column types, so they must have been mapped automatically at some point in the past to and from their ordinal values.  This definitely doesn't happen now - so making the values the ordinal value for SQL queries appears to be the right thing to do.

The only other thing to check is whether anything else accesses these values (in case it causes problems elsewhere).

**Comment by nishihatapalmer** [comment]
Fix merged
