### ISSUE TITLE
BUG: sorting breaks when sorting several nested folders

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#399]
Sometimes sorting breaks completely in the main GUI profile window with the following exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:899)
	at java.util.TimSort.mergeAt(TimSort.java:516)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	at java.util.TimSort.sort(TimSort.java:254)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:175)
	at org.netbeans.swing.outline.Outline.sortAndFilter(Outline.java:493)
	at org.netbeans.swing.etable.ETable.convertRowIndexToView(ETable.java:1605)
```
This implies the comparator isn't transitive (or some other comparison bug is happening).  

I can reproduce the issue reliably on a profile on my own document profile, but I haven't been able to determine yet exactly what is causing it.  Don't want to upload a profile of my own documents, so I'll keep trying to figure out what is causing this.

To try to reproduce it, take any reasonable profile, open various folders up at different levels, and then click column headers to sort by those columns, both ascending and descending and off.  Eventually sorting breaks (I've broken it using the extension column and the size column).  Once broken, it stops working completely for that profile.

**Comment by nishihatapalmer** [comment]
Note: I say "eventually" sorting breaks, but I think it breaks reliably when some condition is satisfied.  I'm wondering if some columns have null values instead of empty, or something like that.  e.g. you have files with file extensions, but some files don't have a file extension.  Not sure yet.

**Comment by nishihatapalmer** [comment]
This bug is in DROID 6.4, so not a result of recent changes.

**Comment by nishihatapalmer** [comment]
And it's in DROID 6.3.  I'm amazed I've never encountered this before.
