### ISSUE TITLE
Command line errors in testing

### ISSUE THREAD

**Issue by Francesca4242** [digital-preservation/droid#439]
I just want to make sure that these errors are standard and nothing unusual. I think they are from corrupted files but you might want to check that?
[log-6.5-command line.txt](https://github.com/digital-preservation/droid/files/4426979/log-6.5-command.line.txt)

**Comment by jcharlet** [comment]
Thanks Francesca for raising this.

I am putting those errors directly in the comment to ease readability.

# errors in text file: to catch and log as WARN
3 types of issues raised in CLI while testing on skeleton suite v96, which could be made quiet.

```
2020-04-03T11:58:42,329 ERROR [core-thread-10] Ole2IdentifierEngine:132 - No reader was obtained for file://na-stor01/homedir$/fmackenzie/Desktop/DROID%20Testing/skeleton-suiteV96/fmt/fmt-111-signature-id-170.nul. This may be due to low memory conditions. Try running with a larger heap size!
```

```
Apr 03, 2020 12:03:39 PM com.github.junrar.Archive setFile
WARNING: exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented
java.lang.NullPointerException
        at com.github.junrar.Archive.readHeaders(Archive.java:291)
        at com.github.junrar.Archive.setFile(Archive.java:169)
        at com.github.junrar.Archive.setVolume(Archive.java:648)
        at com.github.junrar.Archive.<init>(Archive.java:124)
        at com.github.junrar.Archive.<init>(Archive.java:100)
        at uk.gov.nationalarchives.droid.core.interfaces.archive.RarArchiveHandler.handle(RarArchiveHandler.java:103)
        at uk.gov.nationalarchives.droid.submitter.SubmissionGateway.handleArchive(SubmissionGateway.java:269)
        at uk.gov.nationalarchives.droid.submitter.SubmissionGateway.access$700(SubmissionGateway.java:76)
        at uk.gov.nationalarchives.droid.submitter.SubmissionGateway$SubmissionFutureTask.done(SubmissionGateway.java:610)
        at java.base/java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.set(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

```

```
2020-04-03T12:04:44,381  WARN [core-thread-9] SubmissionGateway:282 - Could not process the archival format(7Z): file://na-stor01/homedir$/fmackenzie/Desktop/DROID%20Testing/skeleton-suiteV96/fmt/fmt-484-signature-id-756.7z     null
Apr 03, 2020 12:12:09 PM com.github.junrar.Archive setFile
WARNING: exception in archive constructor maybe file is encrypted, corrupt or support not yet implemented
java.lang.NullPointerException
        at com.github.junrar.Archive.readHeaders(Archive.java:291)
        at com.github.junrar.Archive.setFile(Archive.java:169)
        at com.github.junrar.Archive.setVolume(Archive.java:648)
        at com.github.junrar.Archive.<init>(Archive.java:124)
        at com.github.junrar.Archive.<init>(Archive.java:100)
        at uk.gov.nationalarchives.droid.core.interfaces.archive.RarArchiveHandler.handle(RarArchiveHandler.java:103)
        at uk.gov.nationalarchives.droid.submitter.SubmissionGateway.handleArchive(SubmissionGateway.java:269)
        at uk.gov.nationalarchives.droid.submitter.SubmissionGateway.access$700(SubmissionGateway.java:76)
        at uk.gov.nationalarchives.droid.submitter.SubmissionGateway$SubmissionFutureTask.done(SubmissionGateway.java:610)
        at java.base/java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.set(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

I add to the list a similar issue raised by Ross: 
> CLI exception, might be quieter?
```
$ java -jar droid-command-line-6.5-SNAPSHOT.jar
2020-04-05T13:17:10,919  INFO [main] DroidCommandLine:123 - Starting DROID.
No command line options specified (use -h to see all available options)
Exception in thread "main" uk.gov.nationalarchives.droid.command.action.CommandLineSyntaxException: No command line options specified (use -h to see all available options)
at uk.gov.nationalarchives.droid.command.DroidCommandLine.run(DroidCommandLine.java:141)
at uk.gov.nationalarchives.droid.command.DroidCommandLine.processExecution(DroidCommandLine.java:199)
at uk.gov.nationalarchives.droid.command.DroidCommandLine.main(DroidCommandLine.java:174)
```

# warnings: won't fix

Those warnings below are fine to me, since those skeleton suite files are not real files, and thus can appear corrupted:

```
2020-04-03T12:04:20,360  WARN [core-thread-9] SubmissionGateway:282 - Could not process the archival format(ISO): file://na-stor01/homedir$/fmackenzie/Desktop/DROID%20Testing/skeleton-suiteV96/fmt/fmt-468-signature-id-730.iso   java.io.IOException: Could not deserialize a complete block     Could not deserialize a complete block
2020-04-03T12:04:44,381  WARN [core-thread-9] SubmissionGateway:282 - Could not process the archival format(7Z): file://na-stor01/homedir$/fmackenzie/Desktop/DROID%20Testing/skeleton-suiteV96/fmt/fmt-484-signature-id-756.7z     null
2020-04-03T12:12:11,101  WARN [core-thread-9] SubmissionGateway:282 - Could not process the archival format(GZ): file://na-stor01/homedir$/fmackenzie/Desktop/DROID%20Testing/skeleton-suiteV96/x-fmt/x-fmt-266-signature-id-201.gz null
2020-04-03T12:12:11,603  WARN [core-thread-9] SubmissionGateway:282 - Could not process the archival format(BZ): file://na-stor01/homedir$/fmackenzie/Desktop/DROID%20Testing/skeleton-suiteV96/x-fmt/x-fmt-267-signature-id-340.bz Stream is not in the BZip2 format
2020-04-03T12:12:12,083  WARN [core-thread-9] SubmissionGateway:282 - Could not process the archival format(BZ): file://na-stor01/homedir$/fmackenzie/Desktop/DROID%20Testing/skeleton-suiteV96/x-fmt/x-fmt-268-signature-id-342.bz2        BZip2 block size is invalid
```
