### ISSUE TITLE
Error when running program using the jar files

### ISSUE THREAD

**Issue by timyip3** [digital-preservation/droid#76]
I just have a question: How to configure the signature file for the BinarySignatureIdentifier Class? My situation is when I create BinarySignatureIdentifier Class, It throws FileNotFoundException which is at BinarySignatureIdentifier.init() method. I add all the jar files from DROID in build path.

FYI, here is my code:

File file = new File("./sample/AffixSeal_1st_time.pdf");
		
		RequestMetaData metaData = new RequestMetaData(file.length(), file.lastModified(), file.getName());
		
		RequestIdentifier identifier = new RequestIdentifier(file.toURI());
		
		FileSystemIdentificationRequest fileRequest = new FileSystemIdentificationRequest(metaData, identifier);
		
		
		BinarySignatureIdentifier droid = new BinarySignatureIdentifier();

Here is the exception:

log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: 
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:289)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:163)
	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:215)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:256)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:132)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:96)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:654)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:612)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:509)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:415)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:441)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:468)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:122)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at org.apache.commons.logging.impl.Log4JLogger.getLogger(Log4JLogger.java:289)
	at org.apache.commons.logging.impl.Log4JLogger.<init>(Log4JLogger.java:109)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.commons.logging.impl.LogFactoryImpl.createLogFromClass(LogFactoryImpl.java:1116)
	at org.apache.commons.logging.impl.LogFactoryImpl.discoverLogImplementation(LogFactoryImpl.java:914)
	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:604)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:336)
	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:310)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
	at uk.gov.nationalarchives.droid.core.BinarySignatureIdentifier.<init>(BinarySignatureIdentifier.java:64)
	at test.main(test.java:31)
log4j:ERROR Either File or DatePattern options are not set for appender [FILE].

**Comment by anjackson** [comment]
You have to tell it where the file is before you use it. Here's how I do it in Nanite:

https://github.com/openpreserve/nanite/blob/master/nanite-core/src/main/java/uk/bl/wa/nanite/droid/DroidDetector.java#L221-L222
